[package]
name = "serde"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
askama = "0.10"
thiserror = "1.0"
rusqlite = { version = "0.25.3", features=["bundled"] }
r2d2 = "0.8.9"
r2d2_sqlite = "0.18.0"
serde = { version = "1.0.126", features = ["derive"] }
